### ISSUE TITLE
Host '172.18.0.1' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by alexanderilyin** [tony2001/pinba_engine#64]
Looks like MySQL is not configured properly to be used out of the box.

# `docker-compose.yml`

```
version: '3.2'
services:
  pinba:
    image: tony2001/pinba:latest
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
      - target: 30002
        published: 30002
        protocol: udp
        mode: host
```

# `telnet`

```
AF6428:docker-nginx-pinba ailyin$ telnet localhost 3306
Trying ::1...
Connected to localhost.
Escape character is '^]'.
CHost '172.18.0.1' is not allowed to connect to this MySQL serverConnection closed by foreign host.
```
